### ISSUE TITLE
About update to @rollup/plugin-typescript

### ISSUE THREAD

**Issue by GHLandy** [rollup/rollup-starter-lib#66]
Hello there, I want to upate to @rollup/plugin-typescript from rollup-plugin-typescript, but found it only compile `main.ts` but not the `lunchtime.ts`, `millisecondsUntil.ts`  (as in this repo) in the `cjs` format.

I have look through `https://rollupjs.org/guide` but do not found anything to solve this.

So, I want to know if there is any special configuaration about this problem?

**Comment by ash-r1** [comment]
I met the same problem.

It might be caused by this change: https://github.com/rollup/plugins/blob/master/packages/typescript/CHANGELOG.md#v300

> Add note about old behaviour
> ( It mentions to https://github.com/rollup/plugins/pull/181 )

Does anyone know how to solve this ?

**Comment by felix-kaestner** [comment]
I think the issue seems to be related to how [@rollup/plugin-typescript](https://github.com/rollup/plugins) handles _commonjs_. 
If you switch the `module` option inside `tsconfig.json` to either `es2015` or `ESNext` the problem disappears since typescript will inline the code instead of producing _require_ statements.
If someone can reproduce this, I think an issue should be opened at [@rollup/plugin-typescript](https://github.com/rollup/plugins).
